---
title: "Day 1 Assignment - EDS 221"
author: "Michael Zargari"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(janitor)
```

```{r}
# Loading in the file but read_csv. Usually we will be using read_csv and not anything else (not even read.csv)
stl_lead <- read_csv(here::here("data", 
                                "stl_blood_lead.csv"))

names(stl_lead)
```

```{r}
# Cleaning up the column names
stl_lead_clean <- stl_lead %>% 
  clean_names()

names(stl_lead_clean)
```

```{r}
stl_lead_prop <- stl_lead_clean %>% 
  mutate(prop_white = (white / total_pop) * 100)
```

The higher the population of white children, the less children there are with elevated levels of lead in their blood.

```{r}
white_lead_levels_graph <- ggplot(data = stl_lead_prop, 
                                  aes(x = pct_elevated,
                                  y = prop_white)) +
  geom_point(aes(color = poverty_tot)) +
  scale_color_gradient(low = "blue", high = "orange") +
  labs(x = "Percentage of children with elevated blood lead levels",
       y = "Population of white children")

white_lead_levels_graph
```

```{r}
ggsave(plot = white_lead_levels_graph, 
       here::here("figs", 
                  "percentage-of-lead-in-white-children.png"), 
       width = 6, 
       height = 5)
```

```{r}
white_lead_levels_histogram <- ggplot(data = stl_lead_prop, 
                                  aes(x = pct_elevated)) +
  geom_histogram(fill = "blue",
                 color = "red") +
  labs(y = "Number of elevated lead levels in the blood")

white_lead_levels_histogram
```

```{r}
ggsave(plot = white_lead_levels_histogram, 
       here::here("figs", 
                  "elevated_pct_histogram.jpg"))
```
